[package]
name = "hello_world"
version = "0.1.0"
authors = ["Karol Wójcik <karol.wojcik@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.3.0"
lambda_http = "0.3.0"
